### ISSUE TITLE
How is this any different from sabotage's netbsd-curses?

### ISSUE THREAD

**Issue by firasuke** [oasislinux/netbsd-curses#1]
Hey there,

I salute your efforts and time for porting this to linux.

If I may ask, how does this differ from [sabotage's `netbsd-curses`](https://github.com/sabotage-linux/netbsd-curses)?

**Comment by michaelforney** [comment]
This is just an experiment, I'm not sure if I'll end up using it or not.

The main difference is that it's clear the what differences from upstream are. The `netbsd` branch is just a filtered netbsd repository with no changes created with git-filter-repo, so contains the entire history. I plan to keep that up to date and then periodically merge to master. In sabotage netbsd-curses, it wasn't clear to me what the changes are from upstream, or what procedure to use to update it to the latest version.

Another difference is that the sabotage netbsd-curses uses compatibility headers for various things, while here I'm trying to use portable equivalents if possible.

**Comment by firasuke** [comment]
Thanks for clarifying.
